// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cathedral

import (
	"github.com/vsjcloud/beaver/cathedral/common/config"
	"github.com/vsjcloud/beaver/cathedral/modules/project"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initializeModuleSet(cathedralConfig *config.Cathedral, logger *zap.Logger) (*ModuleSet, error) {
	projectServiceServer := project.NewService()
	moduleSet := &ModuleSet{
		Config:         cathedralConfig,
		Logger:         logger,
		ProjectService: projectServiceServer,
	}
	return moduleSet, nil
}
