/* eslint-disable @typescript-eslint/explicit-function-return-type */
module.exports = {
  prefix: "",
  important: false,
  separator: ":",
  theme: {
    screens: {},
    colors: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",

      black: "#000",
      white: "#fff",

      gray: {
        1: "var(--color-gray-1)",
        2: "var(--color-gray-2)",
        3: "var(--color-gray-3)",
        4: "var(--color-gray-4)",
        5: "var(--color-gray-5)",
        6: "var(--color-gray-6)",
        7: "var(--color-gray-7)",
        8: "var(--color-gray-8)",
        9: "var(--color-gray-9)",
      },
      blue: {
        1: "var(--color-blue-1)",
        2: "var(--color-blue-2)",
        3: "var(--color-blue-3)",
        4: "var(--color-blue-4)",
        5: "var(--color-blue-5)",
      },
      green: {
        1: "var(--color-green-1)",
        2: "var(--color-green-2)",
        3: "var(--color-green-3)",
        4: "var(--color-green-4)",
        5: "var(--color-green-5)",
      },
      orange: {
        1: "var(--color-orange-1)",
        2: "var(--color-orange-2)",
        3: "var(--color-orange-3)",
        4: "var(--color-orange-4)",
        5: "var(--color-orange-5)",
      },
      red: {
        1: "var(--color-red-1)",
        2: "var(--color-red-2)",
        3: "var(--color-red-3)",
        4: "var(--color-red-4)",
        5: "var(--color-red-5)",
      },
    },
    backgroundColor: theme => theme("colors"),
    borderColor: theme => theme("colors"),
    borderRadius: {
      "none": 0,
      "px2": "2px",
      "px4": "4px",
      "full": "9999px",
    },
    boxShadow: {
      "1-light": "var(--shadow-1-light)",
      "1-dark": "var(--shadow-1-dark)",
      "8": "var(--shadow-8)",
      "12": "var(--shadow-12)",
      "none": "none",
    },
    cursor: {
      pointer: "pointer",
      "not-allowed": "not-allowed",
    },
    fill: {
      current: "currentColor",
    },
    flex: {
      "1": "1 1 0%",
      auto: "1 1 auto",
      initial: "0 1 auto",
      none: "none",
    },
    flexGrow: {
      "0": "0",
      default: "1",
    },
    flexShrink: {
      "0": "0",
      default: "1",
    },
    fontFamily: {
      sans: "var(--font-sans)",
    },
    fontSize: {
      "35": "35px",
      "30": "30px",
      "26": "26px",
      "23": "23px",
      "20": "20px",
      "17": "17px",
      "15": "15px",
      "13": "13px",
      "11": "11px",
      "10": "10px",
      "9": "9px",
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    height: {
      px8: "8px",
      px16: "16px",
      px20: "20px",
      px24: "24px",
      px32: "32px",
      px40: "40px",
      px48: "48px",
      px64: "64px",
      px128: "128px",
      px256: "256px",
      pc100: "100%",
      vh100: "100vh",
      auto: "auto",
    },
    inset: {
      "0": "0",
    },
    lineHeight: {
      "16": "16px",
      "20": "20px",
      "24": "24px",
      "28": "28px",
      "32": "32px",
      "40": "40px",
      "44": "44px",
      "r1p5": "1.5",
    },
    margin: {
      "auto": "auto",
      "0": "var(--space-0)",
      "4": "var(--space-4)",
      "8": "var(--space-8)",
      "12": "var(--space-12)",
      "16": "var(--space-16)",
      "20": "var(--space-20)",
      "24": "var(--space-24)",
      "32": "var(--space-32)",
      "40": "var(--space-40)",
      "48": "var(--space-48)",
    },
    maxWidth: {
      px128: "128px",
      px256: "256px",
      px512: "512px",
      px768: "768px",
      px1024: "1024px",
      pc100: "100%",
    },
    minHeight: {
      pc100: "100%",
      vh100: "100vh",
    },
    opacity: {
      "100": " 1",
      "90": ".9",
      "80": ".8",
      "70": ".7",
      "60": ".6",
      "50": ".5",
      "40": ".4",
      "30": ".3",
      "20": ".2",
      "10": ".1",
      "0": " 0",
    },
    padding: {
      "0": "var(--space-0)",
      "4": "var(--space-4)",
      "8": "var(--space-8)",
      "12": "var(--space-12)",
      "16": "var(--space-16)",
      "20": "var(--space-20)",
      "24": "var(--space-24)",
      "32": "var(--space-32)",
      "40": "var(--space-40)",
      "48": "var(--space-48)",
    },
    stroke: {
      current: "currentColor",
    },
    textColor: theme => theme("colors"),
    width: {
      "px8": "8px",
      "px16": "16px",
      "px20": "20px",
      "px32": "32px",
      "px40": "40px",
      "px48": "48px",
      "px64": "64px",
      "px128": "128px",
      "px256": "256px",
      "px512": "512px",
      "px768": "768px",
      "px1024": "1024px",
      "px1536": "1536px",
      "pc10": "10%",
      "pc20": "20%",
      "pc25": "25%",
      "pc30": "30%",
      "pc33": "calc(100% / 3)",
      "pc40": "40%",
      "pc50": "50%",
      "pc60": "60%",
      "pc66": "calc(100% / 1.5)",
      "pc70": "70%",
      "pc75": "75%",
      "pc80": "80%",
      "pc90": "90%",
      "pc100": "100%",
      "auto": "auto",
      "min": "min-content",
      "max": "max-content",
    },
    zIndex: {
      "0": 0,
      "1": 1,
      "2": 2,
      "3": 3,
      "4": 4,
      "5": 5,
      "999": 999,
      "9999": 9999,
    },
  },
  variants: {
    accessibility: false,
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: false,
    backgroundAttachment: false,
    backgroundColor: ["hover", "active"],
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    borderColor: ["hover", "active"],
    borderRadius: false,
    borderStyle: [],
    borderWidth: false,
    boxShadow: ["hover"],
    cursor: [],
    display: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: false,
    fontFamily: [],
    fontSize: [],
    fontSmoothing: false,
    fontStyle: [],
    fontWeight: [],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: false,
    lineHeight: [],
    listStylePosition: false,
    listStyleType: false,
    margin: [],
    maxHeight: false,
    maxWidth: [],
    minHeight: [],
    minWidth: false,
    objectFit: false,
    objectPosition: false,
    opacity: [],
    order: false,
    outline: false,
    overflow: false,
    padding: [],
    placeholderColor: false,
    pointerEvents: [],
    position: [],
    resize: false,
    stroke: [],
    tableLayout: false,
    textAlign: [],
    textColor: ["hover", "active"],
    textDecoration: false,
    textTransform: false,
    userSelect: [],
    verticalAlign: [],
    visibility: false,
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: [],
  },
  corePlugins: {},
  plugins: [],
};
/* eslint-enable @typescript-eslint/explicit-function-return-type */
