// Code generated by protoc-gen-go. DO NOT EDIT.
// source: photo.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhotoResolution struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoResolution) Reset()         { *m = PhotoResolution{} }
func (m *PhotoResolution) String() string { return proto.CompactTextString(m) }
func (*PhotoResolution) ProtoMessage()    {}
func (*PhotoResolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d481429c0c8c32c, []int{0}
}

func (m *PhotoResolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoResolution.Unmarshal(m, b)
}
func (m *PhotoResolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoResolution.Marshal(b, m, deterministic)
}
func (m *PhotoResolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoResolution.Merge(m, src)
}
func (m *PhotoResolution) XXX_Size() int {
	return xxx_messageInfo_PhotoResolution.Size(m)
}
func (m *PhotoResolution) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoResolution.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoResolution proto.InternalMessageInfo

func (m *PhotoResolution) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PhotoResolution) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PhotoResolution) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Photo struct {
	Name                 string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resolutions          map[string]*PhotoResolution `protobuf:"bytes,2,rep,name=resolutions,proto3" json:"resolutions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d481429c0c8c32c, []int{1}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Photo) GetResolutions() map[string]*PhotoResolution {
	if m != nil {
		return m.Resolutions
	}
	return nil
}

func init() {
	proto.RegisterType((*PhotoResolution)(nil), "model.PhotoResolution")
	proto.RegisterType((*Photo)(nil), "model.Photo")
	proto.RegisterMapType((map[string]*PhotoResolution)(nil), "model.Photo.ResolutionsEntry")
}

func init() { proto.RegisterFile("photo.proto", fileDescriptor_0d481429c0c8c32c) }

var fileDescriptor_0d481429c0c8c32c = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc8, 0xc8, 0x2f,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x0a,
	0xe6, 0xe2, 0x0f, 0x00, 0x89, 0x06, 0xa5, 0x16, 0xe7, 0xe7, 0x94, 0x96, 0x64, 0xe6, 0xe7, 0x09,
	0x89, 0x71, 0xb1, 0x65, 0xa4, 0x66, 0xa6, 0x67, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06,
	0x41, 0x79, 0x42, 0x22, 0x5c, 0xac, 0xe5, 0x99, 0x29, 0x25, 0x19, 0x12, 0x4c, 0x60, 0x61, 0x08,
	0x47, 0x48, 0x88, 0x8b, 0xa5, 0x38, 0xb3, 0x2a, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x39, 0x08,
	0xcc, 0x56, 0xda, 0xc2, 0xc8, 0xc5, 0x0a, 0x36, 0x15, 0x24, 0x9b, 0x97, 0x98, 0x9b, 0x0a, 0x36,
	0x89, 0x33, 0x08, 0xcc, 0x16, 0xb2, 0xe7, 0xe2, 0x2e, 0x82, 0xdb, 0x56, 0x2c, 0xc1, 0xa4, 0xc0,
	0xac, 0xc1, 0x6d, 0x24, 0xab, 0x07, 0x76, 0x8f, 0x1e, 0x58, 0x9b, 0x1e, 0xc2, 0x35, 0xc5, 0xae,
	0x79, 0x25, 0x45, 0x95, 0x41, 0xc8, 0x3a, 0xa4, 0xc2, 0xb8, 0x04, 0xd0, 0x15, 0x08, 0x09, 0x70,
	0x31, 0x67, 0xa7, 0x56, 0x42, 0xed, 0x01, 0x31, 0x85, 0x74, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a,
	0x53, 0xc1, 0xce, 0xe5, 0x36, 0x12, 0x43, 0xb6, 0x00, 0xa1, 0x3d, 0x08, 0xa2, 0xc8, 0x8a, 0xc9,
	0x82, 0x31, 0x89, 0x0d, 0x1c, 0x32, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0xf3, 0x78,
	0x0b, 0x28, 0x01, 0x00, 0x00,
}
